<?xml version="1.0" encoding="utf-8"?><Database Name="QuanLyLuongSanPham" Class="QuanLyLuongSanPhamDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-50F1KAT\Peguin;Initial Catalog=QuanLyLuongSanPham;Integrated Security=True" SettingsObjectName="QuanLyLuongSanPham_DAO.Properties.Settings" SettingsPropertyName="QuanLyLuongSanPhamConnectionString5" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TaiKhoan" Member="TaiKhoans">
    <Type Name="TaiKhoan">
      <Column Name="username" Type="System.String" DbType="VarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="passwords" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="maNhanVien" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="quyen" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Association Name="NhanVien_TaiKhoan" Member="NhanVien" ThisKey="maNhanVien" OtherKey="maNhanVien" Type="NhanVien" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="PhanQuyen_TaiKhoan" Member="PhanQuyen" ThisKey="quyen" OtherKey="tenPhanQuyen" Type="PhanQuyen" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CaLamViec" Member="CaLamViecs">
    <Type Name="CaLamViec">
      <Column Name="maCa" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ca" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="CaLamViec_PhanCong" Member="PhanCongs" ThisKey="maCa" OtherKey="maCa" Type="PhanCong" />
      <Association Name="CaLamViec_PhieuChamCongCongNhan" Member="PhieuChamCongCongNhans" ThisKey="maCa" OtherKey="maCa" Type="PhieuChamCongCongNhan" />
    </Type>
  </Table>
  <Table Name="dbo.CongDoanSanXuat" Member="CongDoanSanXuats">
    <Type Name="CongDoanSanXuat">
      <Column Name="soThuTu" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="tenCongDoan" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="donGia" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="maSanPhamSanXuat" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="thuTuCongDoan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="trangThai" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="maRangBuoc" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="ngayBatDau" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ngayKetThuc" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="CongDoanSanXuat_LuongCongNhan" Member="LuongCongNhans" ThisKey="soThuTu" OtherKey="maCongDoan" Type="LuongCongNhan" />
      <Association Name="CongDoanSanXuat_PhanCong" Member="PhanCongs" ThisKey="soThuTu" OtherKey="maCongDoan" Type="PhanCong" />
      <Association Name="SanPhamSanXuat_CongDoanSanXuat" Member="SanPhamSanXuat" ThisKey="maSanPhamSanXuat" OtherKey="maSanPhamSanXuat" Type="SanPhamSanXuat" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ChiTietDonHang" Member="ChiTietDonHangs">
    <Type Name="ChiTietDonHang">
      <Column Name="soLuongBan" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="donGia" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="maDonHang" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="maSanPham" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="DonHang_ChiTietDonHang" Member="DonHang" ThisKey="maDonHang" OtherKey="maDonHang" Type="DonHang" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="SanPham_ChiTietDonHang" Member="SanPham" ThisKey="maSanPham" OtherKey="maSanPham" Type="SanPham" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ChiTietModel" Member="ChiTietModels">
    <Type Name="ChiTietModel">
      <Column Name="thongSoKiThuat" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="moTa" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="maSanPham" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="maModel" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Model_ChiTietModel" Member="Model" ThisKey="maModel" OtherKey="maModel" Type="Model" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="SanPham_ChiTietModel" Member="SanPham" ThisKey="maSanPham" OtherKey="maSanPham" Type="SanPham" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ChungChi" Member="ChungChis">
    <Type Name="ChungChi">
      <Column Name="soThuTu" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="tenChungChi" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Association Name="ChungChi_LuongHanhChanh" Member="LuongHanhChanhs" ThisKey="soThuTu" OtherKey="maChungChi" Type="LuongHanhChanh" />
    </Type>
  </Table>
  <Table Name="dbo.DonHang" Member="DonHangs">
    <Type Name="DonHang">
      <Column Name="maDonHang" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="tenKhachHang" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="soDienThoaiKhachHang" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="ngayBatDau" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ngayKetThuc" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="noiDung" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="maNhanVien" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="trangThai" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="tinhTrangDonHang" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="DonHang_ChiTietDonHang" Member="ChiTietDonHangs" ThisKey="maDonHang" OtherKey="maDonHang" Type="ChiTietDonHang" />
      <Association Name="DonHang_SanPhamSanXuat" Member="SanPhamSanXuats" ThisKey="maDonHang" OtherKey="maDonHang" Type="SanPhamSanXuat" />
      <Association Name="NhanVien_DonHang" Member="NhanVien" ThisKey="maNhanVien" OtherKey="maNhanVien" Type="NhanVien" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DonViQuanLy" Member="DonViQuanLies">
    <Type Name="DonViQuanLy">
      <Column Name="maDonVi" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="tenBoPhan" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="soLuongNhanVien" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="maLoai" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Association Name="DonViQuanLy_PhatNhanVien" Member="PhatNhanViens" ThisKey="maDonVi" OtherKey="maDonVi" Type="PhatNhanVien" />
      <Association Name="LoaiNhanVien_DonViQuanLy" Member="LoaiNhanVien" ThisKey="maLoai" OtherKey="maLoai" Type="LoaiNhanVien" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.LoaiNhanVien" Member="LoaiNhanViens">
    <Type Name="LoaiNhanVien">
      <Column Name="maLoai" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="loaiNhanVien" Member="loaiNhanVien1" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="trangThai" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="LoaiNhanVien_DonViQuanLy" Member="DonViQuanLies" ThisKey="maLoai" OtherKey="maLoai" Type="DonViQuanLy" />
      <Association Name="LoaiNhanVien_NhanVien" Member="NhanViens" ThisKey="maLoai" OtherKey="maLoai" Type="NhanVien" />
      <Association Name="LoaiNhanVien_PhanQuyen" Member="PhanQuyens" ThisKey="maLoai" OtherKey="maLoai" Type="PhanQuyen" />
    </Type>
  </Table>
  <Table Name="dbo.LuongCongNhan" Member="LuongCongNhans">
    <Type Name="LuongCongNhan">
      <Column Name="maLuong" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="thangLuong" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="namLuong" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="soLuongSanPham" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="thue" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="phuCap" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tienUng" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="maTienPhat" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="maNhanVien" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="maPhieu" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="maCongDoan" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="CongDoanSanXuat_LuongCongNhan" Member="CongDoanSanXuat" ThisKey="maCongDoan" OtherKey="soThuTu" Type="CongDoanSanXuat" IsForeignKey="true" />
      <Association Name="MucTienPhat_LuongCongNhan" Member="MucTienPhat" ThisKey="maTienPhat" OtherKey="soThuTu" Type="MucTienPhat" IsForeignKey="true" />
      <Association Name="NhanVien_LuongCongNhan" Member="NhanVien" ThisKey="maNhanVien" OtherKey="maNhanVien" Type="NhanVien" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="PhieuChamCongCongNhan_LuongCongNhan" Member="PhieuChamCongCongNhan" ThisKey="maPhieu" OtherKey="maPhieu" Type="PhieuChamCongCongNhan" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LuongHanhChanh" Member="LuongHanhChanhs">
    <Type Name="LuongHanhChanh">
      <Column Name="maLuong" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="luongCoBan" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="thangLuong" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="namLuong" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="thue" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="phuCap" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tienUng" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tienTangCa" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="maTienPhat" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="soNgayLamDuoc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="maNhanVien" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="maChungChi" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="maPhieu" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Association Name="ChungChi_LuongHanhChanh" Member="ChungChi" ThisKey="maChungChi" OtherKey="soThuTu" Type="ChungChi" IsForeignKey="true" />
      <Association Name="MucTienPhat_LuongHanhChanh" Member="MucTienPhat" ThisKey="maTienPhat" OtherKey="soThuTu" Type="MucTienPhat" IsForeignKey="true" />
      <Association Name="NhanVien_LuongHanhChanh" Member="NhanVien" ThisKey="maNhanVien" OtherKey="maNhanVien" Type="NhanVien" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="PhieuChamCongNhanVienHanhChanh_LuongHanhChanh" Member="PhieuChamCongNhanVienHanhChanh" ThisKey="maPhieu" OtherKey="maPhieu" Type="PhieuChamCongNhanVienHanhChanh" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Model" Member="Models">
    <Type Name="Model">
      <Column Name="maModel" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="tenModel" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="trangThai" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Model_ChiTietModel" Member="ChiTietModels" ThisKey="maModel" OtherKey="maModel" Type="ChiTietModel" />
    </Type>
  </Table>
  <Table Name="dbo.MucTienPhat" Member="MucTienPhats">
    <Type Name="MucTienPhat">
      <Column Name="soThuTu" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="tenKhoanPhat" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="mucTienPhat" Member="mucTienPhat1" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Association Name="MucTienPhat_LuongCongNhan" Member="LuongCongNhans" ThisKey="soThuTu" OtherKey="maTienPhat" Type="LuongCongNhan" />
      <Association Name="MucTienPhat_LuongHanhChanh" Member="LuongHanhChanhs" ThisKey="soThuTu" OtherKey="maTienPhat" Type="LuongHanhChanh" />
      <Association Name="MucTienPhat_PhatNhanVien" Member="PhatNhanViens" ThisKey="soThuTu" OtherKey="maMucPhat" Type="PhatNhanVien" />
    </Type>
  </Table>
  <Table Name="dbo.NhanVien" Member="NhanViens">
    <Type Name="NhanVien">
      <Column Name="maNhanVien" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="tenNhanVien" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="gioiTinh" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="soDienThoai" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="ngaySinh" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="ngayBatDauCongTac" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="trangThai" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="avatar" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="diaChi" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="maLoai" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Association Name="NhanVien_TaiKhoan" Member="TaiKhoans" ThisKey="maNhanVien" OtherKey="maNhanVien" Type="TaiKhoan" />
      <Association Name="NhanVien_DonHang" Member="DonHangs" ThisKey="maNhanVien" OtherKey="maNhanVien" Type="DonHang" />
      <Association Name="NhanVien_LuongCongNhan" Member="LuongCongNhans" ThisKey="maNhanVien" OtherKey="maNhanVien" Type="LuongCongNhan" />
      <Association Name="NhanVien_LuongHanhChanh" Member="LuongHanhChanhs" ThisKey="maNhanVien" OtherKey="maNhanVien" Type="LuongHanhChanh" />
      <Association Name="NhanVien_PhanCong" Member="PhanCongs" ThisKey="maNhanVien" OtherKey="maNhanVien" Type="PhanCong" />
      <Association Name="NhanVien_PhanCong1" Member="PhanCongs1" ThisKey="maNhanVien" OtherKey="maNhanVienPhanCong" Type="PhanCong" />
      <Association Name="NhanVien_PhatNhanVien" Member="PhatNhanViens" ThisKey="maNhanVien" OtherKey="maNhanVien" Type="PhatNhanVien" />
      <Association Name="NhanVien_PhieuChamCongCongNhan" Member="PhieuChamCongCongNhans" ThisKey="maNhanVien" OtherKey="maNhanVien" Type="PhieuChamCongCongNhan" />
      <Association Name="NhanVien_PhieuChamCongNhanVienHanhChanh" Member="PhieuChamCongNhanVienHanhChanhs" ThisKey="maNhanVien" OtherKey="maNhanVien" Type="PhieuChamCongNhanVienHanhChanh" />
      <Association Name="LoaiNhanVien_NhanVien" Member="LoaiNhanVien" ThisKey="maLoai" OtherKey="maLoai" Type="LoaiNhanVien" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PhanCong" Member="PhanCongs">
    <Type Name="PhanCong">
      <Column Name="maPhanCong" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="maNhanVien" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="maCongDoan" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="maCa" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="ngayLam" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="maNhanVienPhanCong" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Association Name="CaLamViec_PhanCong" Member="CaLamViec" ThisKey="maCa" OtherKey="maCa" Type="CaLamViec" IsForeignKey="true" />
      <Association Name="CongDoanSanXuat_PhanCong" Member="CongDoanSanXuat" ThisKey="maCongDoan" OtherKey="soThuTu" Type="CongDoanSanXuat" IsForeignKey="true" />
      <Association Name="NhanVien_PhanCong" Member="NhanVien" ThisKey="maNhanVien" OtherKey="maNhanVien" Type="NhanVien" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="NhanVien_PhanCong1" Member="NhanVien1" ThisKey="maNhanVienPhanCong" OtherKey="maNhanVien" Type="NhanVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PhanQuyen" Member="PhanQuyens">
    <Type Name="PhanQuyen">
      <Column Name="tenPhanQuyen" Type="System.String" DbType="VarChar(200) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="maLoai" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="fullChucNang" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="xem" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="them" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="xoa" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="sua" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="PhanQuyen_TaiKhoan" Member="TaiKhoans" ThisKey="tenPhanQuyen" OtherKey="quyen" Type="TaiKhoan" />
      <Association Name="LoaiNhanVien_PhanQuyen" Member="LoaiNhanVien" ThisKey="maLoai" OtherKey="maLoai" Type="LoaiNhanVien" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PhatNhanVien" Member="PhatNhanViens">
    <Type Name="PhatNhanVien">
      <Column Name="maPhat" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="maNhanVien" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="maMucPhat" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="maDonVi" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="ngayPhat" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="DonViQuanLy_PhatNhanVien" Member="DonViQuanLy" ThisKey="maDonVi" OtherKey="maDonVi" Type="DonViQuanLy" IsForeignKey="true" />
      <Association Name="MucTienPhat_PhatNhanVien" Member="MucTienPhat" ThisKey="maMucPhat" OtherKey="soThuTu" Type="MucTienPhat" IsForeignKey="true" />
      <Association Name="NhanVien_PhatNhanVien" Member="NhanVien" ThisKey="maNhanVien" OtherKey="maNhanVien" Type="NhanVien" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.PhieuChamCongCongNhan" Member="PhieuChamCongCongNhans">
    <Type Name="PhieuChamCongCongNhan">
      <Column Name="maPhieu" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ngayChamCong" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="diLam" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="diTre" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="soLuongSP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="trangThai" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="maNhanVien" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="maCa" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Association Name="PhieuChamCongCongNhan_LuongCongNhan" Member="LuongCongNhans" ThisKey="maPhieu" OtherKey="maPhieu" Type="LuongCongNhan" />
      <Association Name="NhanVien_PhieuChamCongCongNhan" Member="NhanVien" ThisKey="maNhanVien" OtherKey="maNhanVien" Type="NhanVien" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="CaLamViec_PhieuChamCongCongNhan" Member="CaLamViec" ThisKey="maCa" OtherKey="maCa" Type="CaLamViec" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PhieuChamCongNhanVienHanhChanh" Member="PhieuChamCongNhanVienHanhChanhs">
    <Type Name="PhieuChamCongNhanVienHanhChanh">
      <Column Name="maPhieu" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ngayChamCong" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="diLam" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="diTre" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="trangThai" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="maNhanVien" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Association Name="PhieuChamCongNhanVienHanhChanh_LuongHanhChanh" Member="LuongHanhChanhs" ThisKey="maPhieu" OtherKey="maPhieu" Type="LuongHanhChanh" />
      <Association Name="NhanVien_PhieuChamCongNhanVienHanhChanh" Member="NhanVien" ThisKey="maNhanVien" OtherKey="maNhanVien" Type="NhanVien" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SanPham" Member="SanPhams">
    <Type Name="SanPham">
      <Column Name="maSanPham" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="tenSanPham" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="namSanXuat" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="giaBan" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="trangThai" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="SanPham_ChiTietDonHang" Member="ChiTietDonHangs" ThisKey="maSanPham" OtherKey="maSanPham" Type="ChiTietDonHang" />
      <Association Name="SanPham_ChiTietModel" Member="ChiTietModels" ThisKey="maSanPham" OtherKey="maSanPham" Type="ChiTietModel" />
    </Type>
  </Table>
  <Table Name="dbo.SanPhamSanXuat" Member="SanPhamSanXuats">
    <Type Name="SanPhamSanXuat">
      <Column Name="maSanPhamSanXuat" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="maDonHang" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="tenSanPham" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="soLuongSanXuat" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="trangThai" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="SanPhamSanXuat_CongDoanSanXuat" Member="CongDoanSanXuats" ThisKey="maSanPhamSanXuat" OtherKey="maSanPhamSanXuat" Type="CongDoanSanXuat" />
      <Association Name="DonHang_SanPhamSanXuat" Member="DonHang" ThisKey="maDonHang" OtherKey="maDonHang" Type="DonHang" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
</Database>